### ISSUE TITLE
Android 8 (Xiaomi Phones) not playing stream

### ISSUE THREAD

**Issue by obzc** [johnsonsu/react-native-sound-player#43]
Xiaomi mi 5s and mi 8 lite doesn't play a stream on android 8 version devices. Waiting 10 minutes then starts playing.

**Comment by johnsonsu** [comment]
@obzc , I got your email, just gonna past the content here as well:

I need more information before I can find out about the issue since I don’t have the devices you mentioned.

1. Can you make sure the URL you are streaming from is accessible upon immediate request
2. Can you test using a different audio file, maybe a small file like 5mb
3. Test on another android device or different android version to make sure the problem is not in the code

**Comment by obzc** [comment]
1- Package name "react-native-sound-player"
2- The URL I submit is a stream address.
3- Works on other android and ios devices. But "xiaomi 8.0-8.1 android version" does not work. Waiting 10 minutes after its works.

**Comment by johnsonsu** [comment]
I see your problem. Unfortunately I will not be able to offer you much help since I don’t have the devices to reproduce the issue.

However, since the the stream is working fine on other devices, I think there might be some configurations/settings you can adjust on Xiaomi devices.
If that still cannot solve your problem, you might want to try a different library like https://github.com/zmxv/react-native-sound.

**Comment by harishbabu0419** [comment]
In Xiaomi Phones it doesn't working
