### ISSUE TITLE
Multiple event listeners

### ISSUE THREAD

**Issue by dan-lee** [johnsonsu/react-native-sound-player#45]
Hey, first of all great library it's the only one which works without any problems for us!

I've got a question, why is it not possible to add as many event listeners as I'd like? You're deliberately killing off old listeners here:
https://github.com/johnsonsu/react-native-sound-player/blob/b9beda5d5a51cee53fb27f75fcadc1732ed1f17b/index.js#L27-L30

I am using the sound player all over my app (mostly with `playUrl` though) and would love to have more fine grained control than a 'singleton callback'.

In my opinion it would be great to have something similar as the DOM event listener system. What do you think?

Roughly like this:
```js
SoundPlayer.playUrl('https://example.com/some.mp3')

SoundPlayer.addEventListener('URLFinishedLoading', url => {})
SoundPlayer.addEventListener('FileFinishedLoading', (name, type) => {})
```

I am not sure if this is covering all cases but I think it would be a great improvement.

**Comment by johnsonsu** [comment]
Hi @dan-lee , thank you for your suggestions!

That's a great idea, I should definitely include `url`, `name` and `type` in the callbacks. I should be able to get these done this weekend.

Also, I removed the old listener every time because I wanted to make this package super simple. I can do want you wanted by modify the code to store the listeners into an array, but that will put more responsibility to the user of this library, since they will have to control the subscriptions individually. This can make things a little more complicated.

**Comment by dan-lee** [comment]
@johnsonsu Thanks for your reply. I see your concern and would propose something like a one time subscription or maybe returning an unsubscribe callback.
Something like:

```js
SoundPlayer.on('FinishedLoading', …)
SoundPlayer.once('FinishedLoading', …)

// or (similar like actual addEventListener from the DOM)
SoundPlayer.on('FinishedLoading', callback, { once: true })

// or 
const unsubscribe = SoundPlayer.on('FinishedLoading', …)
// later on… 
unsubscribe()
```

**Comment by johnsonsu** [comment]
Sorry for the delay, but the new version is now available with more control over event listeners. Thank you for your support!
